import Patent from "../Types/Patent"

const patents: Patent[] = [
    {
        pto: "DE",
        publication: "DE102014117526A1",
        year: 2021,
        title: "Verwalten von Flugrouten eines segelnden Luftfahrzeugs",
        inventors: "T.M. Lynar, O.J. Smith and J.M. Wagner",
        issued: "July 8, 2021",
    },
    {
        pto: "GB",
        publication: "GB2538207B",
        year: 2020,
        title: "System and method for collaborative vehicle crash planning and sequence deployment",
        inventors: "J.R. Kozloski, C.A. Pickover, T.M. Lynar and J. Wagner",
        issued: "April 22, 2020",
    },
    {
        pto: "GB",
        publication: "GB2549164B",
        year: 2020,
        title: "Detection of translocation events using graphene-based nanopore assemblies",
        inventors: "S.K. Kannam, J.M. Wagner, S. Harrer, C. Schieber, J.S. Baldauf, M. Downton and N.J. Gunn",
        issued: "February 19, 2020",
    },
    ////
    {
        pto: "US",
        publication: "US11195402",
        year: 2021,
        title: "Predictive warning system",
        inventors: "K.-N.D. Tran, J.A. Moros Ortiz, T.M. Lynar and J. Wagner",
        issued: "December 7, 2021",
    },
    {
        pto: "US",
        publication: "US11195132",
        year: 2021,
        title: "System, method and computer program product for characterizing object status and determining a maintenance schedule",
        inventors: "A. Bojovschi, L.I. Rusu and J.M. Wagner",
        issued: "December 7, 2021",
    },
    {
        pto: "US",
        publication: "US11141102",
        year: 2021,
        title: "System and method to measure, analyze, and model pulmonary function and disease utilizing temporal, spatial, and contextual data",
        inventors: "M.C. Hanpton, T.M. Lynar, S. Pandey and J.M. Wagner",
        issued: "October 12, 2021",
    },
    {
        pto: "US",
        publication: "US11074351",
        year: 2021,
        title: "Location specific identity verification system",
        inventors: "M.C. Hampton, T.M. Lynar, J.M. Wagner and S. von Cavallar",
        issued: "July 27, 2021",
    },
    {
        pto: "US",
        publication: "US11021171",
        year: 2021,
        title: "Driving state within a driving environment that includes autonomous and semi-autonomous vehicles",
        inventors: "J. Andres, T.M. Lynar and J. Wagner",
        issued: "June 1, 2021",
    },
    {
        pto: "US",
        publication: "US10979472",
        year: 2021,
        title: "Dynamically altering presentations to maintain or increase viewer attention",
        inventors: "S. von Cavallar, T.M. Lynar and J.M. Wagner",
        issued: "April 13, 2021",
    },
    {
        pto: "US",
        publication: "US10915601",
        year: 2021,
        title: "Personalized particulate matter exposure management using fine-grained weather modeling and optimal control theory",
        inventors: "T.M. Lynar, S.M. Moore, M.E. Roberts, J.M. Wagner and S. Zhuk",
        issued: "February 9, 2021",
    },
    {
        pto: "US",
        publication: "US10885445",
        year: 2021,
        title: "Method and apparatus for intercollaboration of cognitive models",
        inventors: "T. Lynar, G. Slvakumar and J. Wagner",
        issued: "January 5, 2021",
    },
    {
        pto: "US",
        publication: "US10789604",
        year: 2020,
        title: "System, method and computer program product for reality augmenting towards a predefined object",
        inventors: "S. von Cavallar, T.M. Lynar, J.A.M. Ortiz and J.M. Wagner",
        issued: "September 29, 2020",
    },
    {
        pto: "US",
        publication: "US10785546",
        year: 2020,
        title: "Optimizing product placement in a media",
        inventors: "T. Lynar, S. von Cavallar and J. Wagner",
        issued: "September 22, 2020",
    },
    {
        pto: "US",
        publication: "US10764720",
        year: 2020,
        title: "Location determination using device coordination",
        inventors: "F. Jalali, M. Mirmomeni, S. Pervin and J.M. Wagner",
        issued: "September 1, 2020",
    },
    {
        pto: "US",
        publication: "US10762460",
        year: 2020,
        title: "Predictive alerts for individual risk of injury with ameliorative actions",
        inventors: "R. Garnavi, J.R. Kozloski, T.M. Lynar and J.M. Wagner",
        issued: "September 1, 2020",
    },
    {
        pto: "US",
        publication: "US10762459",
        year: 2020,
        title: "Risk detection and peer corrective assistance for risk mitigation within a work environment",
        inventors: "R. Garnavi, J.R. Kozloski, T. Lynar and J. Wagner",
        issued: "September 1, 2020",
    },
    {
        pto: "US",
        publication: "US10755211",
        year: 2020,
        title: "Work schedule creation based on predicted and detected temporal and event based individual risk to maintain cumulative workplace risk below a threshold",
        inventors: "H. Anjomshoa, J.R. Kozloski, T. Lynar and J. Wagner",
        issued: "August 25, 2020",
    },
    {
        pto: "US",
        publication: "US10692112",
        year: 2020,
        title: "Display control system, method, recording medium and display apparatus network",
        inventors: "S. von Cavallar, T.M. Lynar, J.A.M. Ortiz and J.M. Wagner",
        issued: "June 23, 2020",
    },
    {
        pto: "US",
        publication: "US10692013",
        year: 2020,
        title: "Solar irradiation modeling and forecasting using community based terrestrial sky imaging",
        inventors: "M. Abedini, R. Garnavi, T.M. Lynar, C.I.E. Mesiku and J.M. Wagner",
        issued: "June 23, 2020",
    },
    {
        pto: "US",
        publication: "US10653120",
        year: 2020,
        title: "Automated aquaculture pen location",
        inventors: "R.I. Hickson, T.M. Lynar, O.J. Smith, A. Swan and J.M. Wagner",
        issued: "May 19, 2020",
    },
    {
        pto: "US",
        publication: "US10645911",
        year: 2020,
        title: "Automated aquaculture pen location",
        inventors: "R.I. Hickson, T.M. Lynar, O.J. Smith, A. Swan and J.M. Wagner",
        issued: "May 12, 2020",
    },
    // {
    //     pto: "US", publication: "XXXXXX",
    //     year: 2020,
    //     title: "Predicting harmful chemical exposures and implementing corrective actions prior to overexposure",
    //     inventors:
    //         "Predicting harmful chemical exposures and implementing corrective actions prior to overexposure. A.H.E. Eberbach, J.R. Kozloski, T.M. Lynar and J.M. Wagner",
    //     issued: "Issued by USPTOO on May 5, 2020",
    // },
    {
        pto: "US",
        publication: "US10614479",
        year: 2020,
        title: "Attendance verification",
        inventors: "J.K. Dhaliwahl, T.M. Lynar and J.M. Wagner",
        issued: "April 7, 2020",
    },
    {
        pto: "US",
        publication: "US10601679",
        year: 2020,
        title: "Data-centric predictive container migration based on cognitive modelling",
        inventors: "T.M. Lynar, S. Pandey, G. Sivakumar and J. Wagner",
        issued: "March 24, 2020",
    },
    {
        pto: "US",
        publication: "US10542385",
        year: 2020,
        title: "Location determination using device coordination",
        inventors: "F. Jalali, M. Mirmomeni, S. Pervin and J.M. Wagner",
        issued: "January 21, 2020",
    },
    {
        pto: "US",
        publication: "US10517524",
        year: 2019,
        title: "Mining social media for ultraviolet light exposure analysis",
        inventors: "R. Garnavi, T.M. Lynar, S. Pandey, Z. Wang and J.M. Wagner",
        issued: "December 31, 2019",
    },
    {
        pto: "US",
        publication: "US10417568",
        year: 2019,
        title: "Discovering cognition bias toward data presentation styles through file system analysis",
        inventors: "A.K. Baughman, J.R. Kozloski, T.M. Lynar, S. Pandey and J.M. Wagner",
        issued: "September 17, 2019",
    },
    {
        pto: "CN",
        publication: "CN106461584",
        year: 2019,
        title: "使用基于石墨烯的纳米孔组件的移位事件 的检测方法及其系统",
        inventors: "J.S. Baldauf, M. Downton, N.J. Gunn, S. Harrer, S.K. Kannam and J.M. Wagner",
        issued: "August 30, 2019",
    },
    {
        pto: "CN",
        publication: "CN104778294",
        year: 2019,
        title: "管理翱翔飞行器的飞行路线",
        inventors: "T. Lynar, O.J. Smith and J. Wagner",
        issued: "July 11, 2019",
    },
    {
        pto: "US",
        publication: "US10319241",
        year: 2019,
        title: "Managing flight paths of a soaring aircraft with crowd sourcing",
        inventors: "T.M. Lynar, O.J. Smith and J.M. Wagner",
        issued: "June 11, 2019",
    },
    {
        pto: "JP",
        publication: "JP6505093",
        year: 2019,
        title: "ナノポア構造体、及びナノポア構造体内コーティグ を形成する方法",
        inventors: "N. Gunn, J.M. Comeras, P. Rogers and J. Wagner",
        issued: "April 4, 2019",
    },
    {
        pto: "US",
        publication: "US10265011",
        year: 2019,
        title: "Mining social media for ultraviolet light exposure analysis",
        inventors: "R. Garnavi, T.M. Lynar, S. Pandey, Z. Wang and J.M. Wagner",
        issued: "April 23, 2019",
    },
    {
        pto: "US",
        publication: "US10201307",
        year: 2019,
        title: "System and method to measure, analyze, and model pulmonary function and disease utilizing temporal, spatial, and contextual data",
        inventors: "M.C. Hampton, T.M. Lynar, S. Pandey and J.M. Wagner",
        issued: "February 12, 2019",
    },
    {
        pto: "US",
        publication: "US10109214",
        year: 2018,
        title: "Cognitive bias determination and modeling",
        inventors: "A.K. Baughman, J.R. Kozloski, T.M. Lynar, S. Pandey and J.M. Wagner",
        issued: "October 23, 2018",
    },
    {
        pto: "CN",
        publication: "CN105636709",
        year: 2018,
        title: "使用二硫键以形成用于纳米流体设备的可逆的和可重 复使用的涂层",
        inventors: "N. Gunn, J.M. Comeras, P. Rogers and J. Wagner",
        issued: "September 24, 2018",
    },
    {
        pto: "US",
        publication: "US10067935",
        year: 2018,
        title: "Prediction and optimized prevention of bullying and other counterproductive interactions in live and virtual meeting contexts",
        inventors: "A.K. Baughman, J.R. Kozloski, T.M. Lynar, S. Pandey and J.M. Wagner",
        issued: "September 4, 2018",
    },
    {
        pto: "US",
        publication: "US10049286",
        year: 2018,
        title: "Image-based risk estimation",
        inventors: "R. Garnavi, T.M. Lynar, S. Sedai and J.M. Wagner",
        issued: "August 14, 2018",
    },
    {
        pto: "US",
        publication: "US10043548",
        year: 2018,
        title: "Creating a work based on cognitive state",
        inventors: "T.M. Lynar, J.A. Moros Ortiz, S. von Cavallar and J.M. Wagner",
        issued: "August 7, 2018",
    },
    {
        pto: "US",
        publication: "US10032352",
        year: 2018,
        title: "System and method for wearable indication of personal risk within a workplace",
        inventors: "J.R. Kozloski, T.M. Lynar, J.A. Moros Ortiz and J.M. Wagner",
        issued: "July 24, 2018",
    },
    {
        pto: "US",
        publication: "US10025639",
        year: 2018,
        title: "Energy efficient supercomputer job allocation",
        inventors: "J.R. Kozloski, T.M. Lynar, M.D. Nelson and J.M. Wagner",
        issued: "July 17, 2018",
    },
    {
        pto: "US",
        publication: "US10024852",
        year: 2018,
        title: "Use of disulfide bonds to form a reversible and reusable coating for nanofluidic devices",
        inventors: "N. Gunn, J.M. Lobez Comeras, P. Rogers and J. Wagner",
        issued: "July 17, 2018",
    },
    {
        pto: "US",
        publication: "US10024851",
        year: 2018,
        title: "Use of disulfide bonds to form a reversible and reusable coating for nanofluidic devices",
        inventors: "N. Gunn, J.M. Lobez Comeras, P. Rogers and J. Wagner",
        issued: "July 17, 2018",
    },
    {
        pto: "US",
        publication: "US9953029",
        year: 2018,
        title: "Prediction and optimized prevention of bullying and other counterproductive interactions in live and virtual meeting contexts",
        inventors: "A.K. Baughman, J.R. Kozloski, T.M. Lynar, S. Pandey and J.M. Wagner",
        issued: "April 24, 2018",
    },
    {
        pto: "US",
        publication: "US9947229",
        year: 2018,
        title: "Managing flight paths of a soaring aircraft",
        inventors: "T.M. Lynar, O.J. Smith and J.M. Wagner",
        issued: "April 17, 2018",
    },
    {
        pto: "US",
        publication: "US9934674",
        year: 2018,
        title: "Informing first responders based on incident detection, and automatic reporting of individual location and equipment state",
        inventors: "J.R. Kozloski, T. Lynar, O. Smith and J. Wagner",
        issued: "April 3, 2018",
    },
    {
        pto: "US",
        publication: "US9921181",
        year: 2018,
        title: "Detection of translocation events using graphene-based nanopore assemblies",
        inventors: "J.S. Baldauf, M. Downton, N. Gunn, S. Harrer, S. Kannam, C. Schieber and J. Wagner",
        issued: "March 20, 2018",
    },
    {
        pto: "CN",
        publication: "CN104731658",
        year: 2018,
        title: "供应和合并共享资源以最大化资源可性的方 法和系统",
        inventors: "D. Karunamoorthy, T. Lynar, S. Pandey and J. Wagner",
        issued: "January 11, 2018",
    },
    {
        pto: "US",
        publication: "US9848269",
        year: 2017,
        title: "Predicting harmful noise events and implementing corrective actions prior to noise induced hearing loss",
        inventors: "Eberbach, J.R. Kozloski, T. Lynar and J. Wagner",
        issued: "December 18, 2017",
    },
    {
        pto: "US",
        publication: "US9791453",
        year: 2017,
        title: "Methods for determining binding capability of target ligands with g protein-coupled receptors using translocation through nanochannels",
        inventors: "M. Downton, N. Gunn, S. Harrer, P. Rogers, N. Gunn and J. Wagner",
        issued: "October 16, 2017",
    },
    {
        pto: "US",
        publication: "US9785749",
        year: 2017,
        title: "Machine training and search engine for providing specialized cognitive healthcare apparatus",
        inventors: "M. Abedini, R. Chakravorty, L. Ghahremanlou, S. Pervin and J.M. Wagner",
        issued: "October 10, 2017",
    },
    {
        pto: "US",
        publication: "US9762655",
        year: 2017,
        title: "Directing communications to nodes of a social network using an elastic map",
        inventors: "J.R. Kozloski, T.M. Lynar, C.A. Pickover and J.M. Wagner",
        issued: "September 17, 2017",
    },
    {
        pto: "US",
        publication: "US9760686",
        year: 2017,
        title: "Balanced ultraviolet light exposure recommendations",
        inventors: "R. Garnavi, T. Lynar, S. Pandey, Z. Wang and J. Wagner",
        issued: "September 11, 2017",
    },
    {
        pto: "US",
        publication: "US9691262",
        year: 2017,
        title: "Informing first responders based on incident detection, and automatic reporting of individual location and equipment state",
        inventors: "J.R. Kozloski, T. Lynar, O.J. Smith and J. Wagner",
        issued: "June 26, 2017",
    },
    {
        pto: "US",
        publication: "US9633538",
        year: 2017,
        title: "System and method for wearable indication of personal risk within a workplace",
        inventors: "J.R. Kozloski, T. Lynar, J. Moros Ortiz and J. Wagner",
        issued: "April 24, 2017",
    },
    {
        pto: "US",
        publication: "US9599986",
        year: 2017,
        title: "Emergency automated vehicle control system to monitor emergency medical events through body area networks",
        inventors: "Eberbach, C. Whitehead and J. Wagner",
        issued: "March 20, 2017",
    },
    {
        pto: "US",
        publication: "US9590917",
        year: 2017,
        title: "Optimally provisioning and merging shared resources to maximize resource availability",
        inventors: "D. Karunamoorthy, T. Lynar, S. Pandey and J. Wagner",
        issued: "March 6, 2017",
    },
    {
        pto: "US",
        publication: "US9554744",
        year: 2017,
        title: "Mining social media for ultraviolet light exposure analysis",
        inventors: "R. Garnavi, T. Lynar, S. Pandey, Z. Wang and J. Wagner",
        issued: "January 30, 2017",
    },
    {
        pto: "US",
        publication: "US9481460",
        year: 2016,
        title: "Drone-based microbial analysis system",
        inventors: "J.R. Kozloski, T.M. Lynar, C.A. Pickover and J.M. Wagner",
        issued: "November 1, 2016",
    },
    {
        pto: "US",
        publication: "US9424532",
        year: 2016,
        title: "Machine training and search engine for providing specialized cognitive healthcare apparatus",
        inventors: "M. Abedini, R. Chakravorty, L. Ghahremanlou, S. Pervin and J. Wagner",
        issued: "August 23, 2016",
    },
    {
        pto: "US",
        publication: "US9417928",
        year: 2016,
        title: "Energy efficient supercomputer job allocation",
        inventors: "J.R. Kozloski, T. Lynar, M.D. Nelson and J. Wagner",
        issued: "August 16, 2016",
    },
    {
        pto: "US",
        publication: "US9292635",
        year: 2016,
        title: "System and method for collaborative vehicle crash planning and sequence deployment",
        inventors: "J.R. Kozloski, T. Lynar, C. Pickover and J. Wagner",
        issued: "March 22, 2016",
    },
    {
        pto: "US",
        publication: "US9280385",
        year: 2016,
        title: "Optimally provisioning and merging shared resources to maximize resource availability",
        inventors: "D. Karunamoorthy, T. Lynar, S. Pandey and J. Wagner",
        issued: "March 08, 2016",
    },
    {
        pto: "US",
        publication: "US9108582",
        year: 2015,
        title: "System and method for collaborative vehicle crash planning and sequence deployment",
        inventors: "J.R. Kozloski, T. Lynar, C. Pickover and J. Wagner",
        issued: "August 18, 2015",
    },
    {
        pto: "US",
        publication: "US9110661",
        year: 2015,
        title: "Mobile device offloading task to a peer device and receiving a completed task when energy level is below a threshold level",
        inventors: "T. Lynar, K. Steer, C. Vecchiola and J. Wagner",
        issued: "August 18, 2015",
    },
    {
        pto: "US",
        publication: "US9104412",
        year: 2015,
        title: "Mobile device offloading its task to a peer device when available power is below a threshold level",
        inventors: "T. Lynar, K. Steer, C. Vecchiola and J. Wagner",
        issued: "August 11, 2015",
    },
    {
        pto: "US",
        publication: "US8943361",
        year: 2015,
        title: "Geospatial optimization for resilient power management equipment",
        inventors: "T. Lynar, K. Steer and J. Wagner",
        issued: "January 27, 2015",
    },
    {
        pto: "US",
        publication: "US8835362",
        year: 2014,
        title: "Modifying single proteins (gpcr), ligands, and nanopore surfaces to create binding-induced molecular changes of protein-ligand complexes detected in nanochannel translocation",
        inventors: "M. Downton, N. Gunn, S. Harrer, P. Rogers and J. Wagner",
        issued: "September 16, 2014",
    },
    {
        pto: "US",
        publication: "US8271414",
        year: 2012,
        title: "Network characterization, feature extraction and application to classification",
        inventors: "G. Cecchi, A. Rao, G. Stolovitzky and J. Wagner",
        issued: "September 18, 2012",
    },
]

export default patents
