const professionalExperience = [
    {
        label: "AURL",
        dates: "2019 - 2021",
        title: "Research Staff Member",
        organisation: "IBM Research-Australia, AI for the Eye/Healthcare, Melbourne, VIC",
        duties: "Working with the entire AI for the Eye team, led the development of a software platform for showcasing all of the lab’s research as well as the development of a proof-of-concept diagnostic ophthalmology project in explainable AI using deep learning and machine learning based analysis of fundus and optical coherence tomography imaging of the retina.",
    },
    {
        label: "AURL",
        dates: "2017 - 2019",
        title: "Research Staff Member",
        organisation: "IBM Research-Australia, Blockchain Research and Development, Melbourne, VIC",
        duties: "Performed blockchain research and development, including front end software engineering on large commercial venture in finance and technical leadership of a successful proof-of-concept project in international transport and supply chain involving IBM teams in three countries.",
    },
    {
        label: "AURL",
        dates: "2015 - 2017",
        title: "Manager and Research Staff Member",
        organisation: "IBM Research-Australia, Computational Biology/Healthcare, Melbourne, VIC",
        duties: "Managed the IBM Research Australia’s Computational Biophysics team; performed extensive recruiting, interviewing, hiring and mentoring of staff and student researchers; contributed extensively to the lab’s healthcare and life sciences research and business strategies and portfolios; worked across business units on client engagements; and performed extensive patenting, mentoring of new inventors and service to IBM’s intellectual property processes.",
    },
    {
        label: "AURL",
        dates: "2015 - 2016",
        title: "Honorary Fellow",
        organisation: "Department of Electrical and Electronic Engineering, University of Melbourne, Melbourne, VIC",
        duties: "Taught full courses and sections of courses, co-supervised students and worked with faculty and students on accessing and using the Blue Gene/P and Q systems at the Victorian Life Sciences Computation Initiative, including parallelising and optimising their research codes.",
    },
    {
        label: "Collaboratory",
        dates: "2012 - 2015",
        title: "Scientific Advisory Committee Member",
        organisation: "Centre for Neural Engineering, University of Melbourne, Melbourne, VIC",
        duties: "Advised the Centre’s management on scientific and business strategy and provided feedback on the Centre’s research, particularly with an industry and industrial applied research perspective.",
    },
    {
        label: "Collaboratory",
        dates: "2011 - 2014",
        title: "Senior Fellow",
        organisation: "Department of Electrical and Electronic Engineering, University of Melbourne, Melbourne, VIC",
        duties: "Taught full courses and sections of courses, co-supervised students and worked with faculty and students on accessing and using the Blue Gene/P and Q systems at the Victorian Life Sciences Computation Initiative, including parallelising and optimising their research codes.",
    },
    {
        label: "Collaboratory",
        dates: "2010 - 2014",
        title: "Manager and Research Staff Member",
        organisation: "IBM Research Collaboratory for Life Sciences-Melbourne, Melbourne, VIC",
        duties: "Managed a team of seven full-time researchers and Blue Gene support staff as key partners of the Victorian Life Sciences Computation Initiative; oversaw and managed the delivery and maintenance of two generations of Blue Gene supercomputers offering life sciences compute cycles to Victoria; formulated and managed Collaboratory’s multidisciplinary computational life sciences research strategy and projects; recruited, managed and mentored the Collaboratory’s student research interns; led and performed computational life sciences research in multiple disciplines; and recruited, interviewed, hired and/or mentored over a hundred research staff members and student researchers for the IBM Research Australia lab.",
    },
    {
        label: "Collaboratory",
        dates: "2010 - 2013",
        title: "Honorary Fellow",
        organisation: "Department of Mathematics and Statistics, University of Melbourne, Melbourne, VIC",
        duties: "Taught sections of courses and worked with faculty and students on accessing and using the Blue Gene/P system at the Victorian Life Sciences Computation Initiative, including parallelising and optimising their research codes.",
    },
    {
        label: "Watson",
        dates: "2004 - 2010",
        title: "Long-Term Supplemental",
        organisation: "Computational Biology Center, IBM T.J. Watson Research Center, Yorktown Heights, NY",
        duties: "Performed mathematical and computational modelling research on p53 signalling in cancer; developed numerical and computational approaches and algorithms for large-scale neural tissue simulation on Blue Gene/L supercomputers; and worked with a large team across many IBM business units and geographies to develop and land a large partnership deal with the University of Melbourne.",
    },
    {
        label: "UConn",
        dates: "2000 - 2004",
        title: "NIH NRSA Postdoctoral Fellow",
        organisation: "Department of Physiology, University of Connecticut Health Center, Farmington, CT",
        duties: "Applied for and received NIH NRSA Postdoctoral Fellowship and performed wet lab and computational modelling research on calcium and inositol trisphosphate signalling in Xenopus laevis eggs following fertilisation.",
    },
    {
        label: "UConn",
        dates: "1999 - 2004",
        title: "Postdoctoral Fellow",
        organisation:
            "National Resource for Cell Analysis and Modeling, Department of Physiology, University of Connecticut Health Center, Farmington, CT",
        duties: "Working within a large team of software developers and biologists, performed full-stack software engineering and computational science on The Virtual Cell Project: designed and implemented parallel and single-core numerical and computational algorithms for cellular analysis and spatial modelling; designed, built and maintained Center’s first parallel computing infrastructure, a sixteen-node DEC Alpha-based Beowulf cluster; and designed, implemented and maintained The Virtual Cell Project’s java- and C++-based software codebase.",
    },
    {
        label: "UCDavis",
        dates: "1998 - 1999",
        title: "Scientific Programmer/Programmer IV",
        organisation: "Institute of Theoretical Dynamics, University of California, Davis, Davis, CA",
        duties: "Designed, built and maintained Institute’s first parallel computing infrastructure, a sixteen-node DEC Alpha-based Beowulf cluster; performed extensive training of all of the Institute’s faculty, postdocs and students using the cluster; and performed collaborative scientific research using this system.",
    },
    {
        label: "UCDavis",
        dates: "1994 - 1997",
        title: "Research Assistant",
        organisation: "Information Center for the Environment, University of California, Davis, Davis, CA",
        duties: "Performed full-stack software engineering and web development on a range of environmental projects, including California’s first environmental toxicology database developed in conjunction with the California Governor’s Office for Planning and Research.",
    },
    {
        label: "UCDavis",
        dates: "1994 - 1995",
        title: "Teaching Assistant / Associate-in-Teaching",
        organisation: "Department of Mathematics, University of California, Davis, Davis, CA",
        duties: "Taught undergraduate course in ordinary differential equations course of 68 students and received departmental citation for excellence in teaching.",
    },
    {
        label: "UCDavis",
        dates: "1992 - 1998",
        title: "Research Assistant",
        organisation: "Institute of Theoretical Dynamics, University of California, Davis, Davis, CA",
        duties: "Performed collaborative scientific research in cellular calcium buffering and signalling and designed, built and maintained Institute’s entire computational infrastructure (workstations, PCs and laptops) used by Institute’s research faculty and staff.",
    },
    {
        label: "UCDavis",
        dates: "1989 - 1992",
        title: "Site Aide / Postgraduate Researcher",
        organisation: "Institute of Theoretical Dynamics, University of California, Davis, Davis, CA",
        duties: "Performed collaborative scientific research in healthcare, life sciences, chemistry and physics and maintained Institute’s entire computational infrastructure (workstations, PCs and laptops) used by Institute’s research faculty and staff.",
    },
    {
        label: "Nixdorf",
        dates: "1988",
        title: "Praktikant/Software Developer",
        organisation: "Product Marketing and Support, Nixdorf Computer AG, Paderborn, Germany",
        duties: "Full-stack software engineer on Project Management System used across Nixdorf’s entire Product Marketing and Support team. Designed, developed and delivered C- and SQL-based system in two months.",
    },
]

export default professionalExperience
