import Role from "../Types/Role"

const professionalExperience: Role[] = [
    {
        label: "AURL",
        dates: "2019 - 2021",
        from: "2019",
        to: "2021",
        title: "Research Staff Member",
        organisation: "IBM Research-Australia, AI for the Eye/Healthcare, Melbourne, VIC",
        duties: "Collaborating with the entire AI for the Eye team, led development of software platforms to showcase the team’s research.",
        // "DELETE THE REST: Working with the entire AI for the Eye team, led the development of a software platform for showcasing all of the lab’s research as well as the development of a proof-of-concept diagnostic ophthalmology project in explainable AI using deep learning and machine learning based analysis of fundus and optical coherence tomography imaging of the retina.",
        bullets: [
            "AI for the Eye Demonstration Platform: Led software engineering team working with a team of 10 researchers to build and deliver demonstration platform showcasing 8 research projects into AI for retinal eye diseases.",
            "Artificial Intelligence in Diagnostic Ophthalmology: Led software engineering team working with a team of 7 researchers to develop a prototype artificial analysis (AI) and machine learning (ML) based platform for digital diagnostic ophthalmology and explainable artificial intelligence.",
        ],
    },
    {
        label: "AURL",
        dates: "2017 - 2019",
        from: "2017",
        to: "2019",
        title: "Research Staff Member",
        organisation: "IBM Research-Australia, Blockchain Research and Development, Melbourne, VIC",
        duties: "Performed blockchain research and development, including front-end software engineering on large commercial venture in finance and technical leadership of a successful proof-of-concept project in international transport and supply chain involving IBM teams in 3 countries. Received IBM Master Inventor Award.",
        bullets: [
            "Project Lygon: a Digital Platform for Lifecycle Management of Bank Guarantees: Worked as front-end software engineer within a team of 6 software engineers from IBM and ANZ Bank to build first-of-a-kind prototype blockchain based platform for streamlining the issuance and lifecycle management of bank guarantees. Worked as front-end software engineer on subsequent commercial product. Received IBM Research Division award.",
            "Fair Resource Allocation and Scheduling in Global Transport: Worked as client-facing Engineering Technical Lead of 12 IBM designers and engineers on 3 continents designing and building multi-language prototype blockchain (Hyperledger Fabric) based platform in successful bid for subsequent commercialization.",
        ],
    },
    {
        label: "AURL",
        dates: "2015 - 2017",
        from: "2015",
        to: "2017",
        title: "Manager and Research Staff Member",
        organisation: "IBM Research-Australia, Computational Biology/Healthcare, Melbourne, VIC",
        duties: "Managed the IBM Research Australia’s Computational Biophysics team, including recruiting, interviewing, hiring, and mentoring of research staff and student researchers. Performed extensive computational life sciences and healthcare research and patenting, in addition to mentoring new inventors. Received IBM Master Inventor Award.",
        bullets: [
            "Led formulation and development of healthcare team strategy 'AI for the Eye' focusing on artificial intelliigence in diagnostic opthalmology.",
            "Developed cloud-based platforms for personalised weather forecasting and neuronal modelling.",
            "Action Potential Back-Propagation in Dendritic Spines: built mathematical and multicompartment computational model investigating modification of action potential back-propagation.",
        ],
    },
    {
        label: "AURL",
        dates: "2015 - 2016",
        from: "2015",
        to: "2016",
        title: "Honorary Fellow",
        organisation: "Department of Electrical and Electronic Engineering, University of Melbourne, Melbourne, VIC",
        duties: "Facilitated the instruction of student courses, co-supervised students and worked with faculty and students on accessing and using the Blue Gene/P and Q systems at the Victorian Life Sciences Computation Initiative.",
        bullets: [
            "Taught graduate courses on parallel and multicore computing and neural information processing.",
            "Co-supervised graduate and undergraduate students in life sciences, engineering and mathematics.",
            "Feedback and Crosstalk in TGF-β and IL-6 Mediated Pathways in Cancer: Modelled and analyzed the feedback in and crosstalk between these 2 signaling pathways to better understand their dysregulation in colorectal cancer.",
        ],
    },
    {
        label: "Collaboratory",
        dates: "2012 - 2015",
        from: "2012",
        to: "2015",
        title: "Scientific Advisory Committee Member",
        organisation: "Centre for Neural Engineering, University of Melbourne, Melbourne, VIC",
        duties: "Advised the Centre’s management on scientific and business strategy and provided feedback on the Centre’s research, particularly with an industry engagement and industrial applied research perspective.",
        bullets: [],
    },
    {
        label: "Collaboratory",
        dates: "2011 - 2014",
        from: "2011",
        to: "2014",
        title: "Senior Fellow",
        organisation: "Department of Electrical and Electronic Engineering, University of Melbourne, Melbourne, VIC",
        duties: "Facilitated the instruction of student courses, co-supervised students and worked with faculty and students on accessing and using the Blue Gene/P and Q systems at the Victorian Life Sciences Computation Initiative.",
        bullets: [
            "Taught graduate courses on parallel and multicore computing and neural information processing.",
            "Co-supervised graduate and undergraduate students in life sciences, engineering and mathematics.",
        ],
    },
    {
        label: "Collaboratory",
        dates: "2010 - 2014",
        from: "2010",
        to: "2014",
        title: "Manager and Research Staff Member",
        organisation: "IBM Research Collaboratory for Life Sciences-Melbourne, Melbourne, VIC",
        duties: "Managed 7 full-time researchers and Blue Gene support staff as key partners of the Victorian Life Sciences Computation Initiative. Formulated and managed the multidisciplinary computational life sciences research strategy and projects.",
        bullets: [
            "Oversaw delivery and maintenance of 2 generations of Blue Gene (BG/P and BG/Q) supercomputers offering life sciences compute cycles to scientists in Victoria. Held overall responsibility for meeting all contractual obligations.",
            "Development of Next Generation Nanosensors and Nanofluidic Devices for Drug Screening: Co-led a team of computational biologists, protein scientists and nanotechnology researchers. Performed proof of concept development of a nanopore-based system for screening of ligand activation of a g-protein-coupled receptor.",
            "Computational Modelling of Proteins in Essential Pathways for Antibiotic Development:  Characterized the bacterial and plant lysine biosynthesis pathway at the atomic level using molecular dynamics simulation to demonstrate the integration of high-performance computing-based protein modelling and simulation workflows into a wet lab/synchrotron-based workflow for basic antibiotic research and development. Received IBM Research Division award.",
            "Computational Studies of Cellulose and Cellulose Synthase Enzymes: Led a computational team working with an Australian Research Council Centre of Excellence in Plant Cell Walls at The University of Adelaide, The University of Melbourne and The University of Queensland to develop large-scale, high performance computational models of cellulose and cellulose microfibrils, as well as cellulose synthase and cellulose synthase-like enzymes.",
            "Recruited, interviewed, hired and mentored 100+ research staff members and student researchers for IBM Research-Australia.",
        ],
    },
    {
        label: "Collaboratory",
        dates: "2010 - 2013",
        from: "2010",
        to: "2013",
        title: "Honorary Fellow",
        organisation: "Department of Mathematics and Statistics, University of Melbourne, Melbourne, VIC",
        duties: "Facilitated the instruction of student courses, co-supervised students and worked with faculty and students on accessing and using the Blue Gene/P and Q systems at the Victorian Life Sciences Computation Initiative.",
        bullets: [
            "Taught graduate courses on parallel and multicore computing and neural information processing.",
            "Co-supervised graduate and undergraduate students in life sciences, engineering and mathematics.",
        ],
    },
    {
        label: "Watson",
        dates: "2004 - 2010",
        from: "2004",
        to: "2010",
        title: "Long-Term Supplemental",
        organisation: "Computational Biology Center, IBM T.J. Watson Research Center, Yorktown Heights, NY",
        duties: "Performed multidisciplinary computational life sciences research in cancer biology and neuroscience, including p53 signaling, tumorigenesis and ultra-scalable, large-scale neural tissue simulation.",
        bullets: [
            "Co-led IBM Research’s successful response to Victorian Life Sciences Computation Initiative’s RFP for commercial technology and research partner. Defined the structure of the research engagement and co-negotiated contracts.",
        ],
    },
    {
        label: "UCHC",
        dates: "2000 - 2004",
        from: "2000",
        to: "2004",
        title: "NIH NRSA Postdoctoral Fellow",
        organisation: "Department of Physiology, University of Connecticut Health Center, Farmington, CT",
        duties: "Performed multidisciplinary mathematical, computational and experimental research on fertilisation in Xenopus laevis eggs.",
        bullets: [
            "Applied for and received NIH NRSA Postdoctoral Fellowship to investigate calcium and inositol trisphosphate signalling mechanisms in Xenopus laevis eggs following fertilisation.",
            "Performed wet lab experiments using microinjection of fluorescent calcium and inositol trisphophate indicator dyes and analysed data.",
            "Investigated and published mathematical and high performance computational models of calcium and inositol trisphosphate signalling pathways.",
        ],
    },
    {
        label: "UCHC",
        dates: "1999 - 2004",
        from: "1999",
        to: "2004",
        title: "Postdoctoral Fellow",
        organisation:
            "National Resource for Cell Analysis and Modeling, Department of Physiology, University of Connecticut Health Center, Farmington, CT",
        duties: "Working within a large team of software developers and biologists, performed full-stack software engineering and computational science on The Virtual Cell Project.",
        bullets: [
            "Designed and implemented parallel and single-core numerical and computational algorithms for cellular analysis and spatial modelling.",
            "Designed, built and maintained Center’s first parallel computing infrastructure, a sixteen-node DEC Alpha-based Beowulf cluster.",
            "Designed, implemented and maintained The Virtual Cell Project’s java- and C++-based software codebase.",
        ],
    },
    {
        label: "UCDavis",
        dates: "1998 - 1999",
        from: "1998",
        to: "1999",
        title: "Scientific Programmer/Programmer IV",
        organisation: "Institute of Theoretical Dynamics, University of California, Davis, Davis, CA",
        duties: "Design and construction of Institute's high performance computing facility.",
        bullets: [
            "Designed, built and maintained Institute’s first parallel computing infrastructure, a sixteen-node DEC Alpha-based Beowulf cluster.",
            "Performed extensive training of all of the Institute’s faculty, postdocs and students using the cluster.",
            "Performed collaborative scientific research using this system.",
        ],
    },
    {
        label: "UCDavis",
        dates: "1994 - 1997",
        from: "1994",
        to: "1997",
        title: "Research Assistant",
        organisation: "Information Center for the Environment, University of California, Davis, Davis, CA",
        duties: "Performed full-stack software engineering and web development on a range of environmental projects, including California’s first environmental toxicology database developed in conjunction with the California Governor’s Office for Planning and Research.",
        bullets: [],
    },
    {
        label: "UCDavis",
        dates: "1994 - 1995",
        from: "1994",
        to: "1995",
        title: "Teaching Assistant / Associate-in-Teaching",
        organisation: "Department of Mathematics, University of California, Davis, Davis, CA",
        duties: "Taught undergraduate course in ordinary differential equations course of 68 students and received departmental citation for excellence in teaching.",
        bullets: [],
    },
    {
        label: "UCDavis",
        dates: "1992 - 1998",
        from: "1992",
        to: "1998",
        title: "Research Assistant",
        organisation: "Institute of Theoretical Dynamics, University of California, Davis, Davis, CA",
        duties: "Performed collaborative scientific research in cellular calcium buffering and signalling.",
        bullets: [
            "Derived, analysed and published a complete mathematical theory of the rapid buffering of calcium in cells.",
            "Derived, analysed and published a spatiotemporal mathematical of the fertilisation calcium wave in Xenopus laevis eggs.",
            "designed, built and maintained Institute’s entire computational infrastructure (workstations, PCs and laptops) used by Institute’s research faculty and staff.",
        ],
    },
    {
        label: "UCDavis",
        dates: "1989 - 1992",
        from: "1989",
        to: "1992",
        title: "Site Aide / Postgraduate Researcher",
        organisation: "Institute of Theoretical Dynamics, University of California, Davis, Davis, CA",
        duties: "Performed collaborative scientific research in healthcare, life sciences, chemistry and physics and maintained Institute’s entire computational infrastructure (workstations, PCs and laptops) used by Institute’s research faculty and staff.",
        bullets: [
            "Using data we collected from patients in the UC Davis Medical Center haemodialysis clinic, constructed and published patient-specific mathematical models of urea dynamics during and between treatments.",
            "Developed and published mathematical models of the effects of molecular fluctuations in physical systems exhibiting chaotic dynamics.",
        ],
    },
    {
        label: "Nixdorf",
        dates: "1988",
        from: "1988",
        to: "1988",
        title: "Praktikant/Software Developer",
        organisation: "Product Marketing and Support, Nixdorf Computer AG, Paderborn, Germany",
        duties: "Full-stack software engineer on Project Management System used across Nixdorf’s entire Product Marketing and Support team.",
        bullets: [
            "Designed, developed and delivered C- and SQL-based system in two months.",
            "Provided customer support to German-speaking banking customers across Germany, Austria and Switzerland.",
        ],
    },
]

export default professionalExperience
