import Publication from "../Types/Publication"

const publications: Publication[] = [
    {
        key: "UnderReview",
        topics: ["Machine Learning", "Genomics"],
        authors: "J. Dhaliwal and J. Wagner",
        title: "Feature extraction and selection by STR enrichment in machine learning for gene prediction",
        journal: "Pattern Recognition",
        volume: "(under review)",
        year: 2022,
    },
    {
        key: "DhaliwalWagner2021",
        topics: ["Machine Learning", "Genomics"],
        authors: "J. Dhaliwal and J. Wagner",
        title: "A novel feature extraction method based on highly expressed SNPs for tissue-specific gene prediction",
        journal: "Journal of Big Data",
        volume: "8(1): 1—13, 2021",
        impact: "2021 Impact Factor: 11.092",
        url: "https://doi.org/10.1186/s40537-021-00497-9",
        year: 2021,
    },
    {
        key: "AlamTran2019",
        topics: ["Machine Learning"],
        authors: "N. Alam, K.-N. Tran, S.A. Chen, J. Wagner, J. Andres and M. Mohania",
        title: "Towards a predictive analytics evaluation platform",
        journal: "ECML-PKDD",
        volume: "2019",
        url: "https://arxiv.org/abs/1910.14258",
        year: 2019,
    },
    {
        key: "KeatingWaltemath2020",
        topics: ["SBML"],
        authors: "S.M. Keating et al (52 authors including J. Wagner)",
        title: "SBML Level 3: an extensible format for the exchange and reuse of biological models",
        journal: "Molecular Systems Biology",
        volume: "16: e9110, 2020",
        impact: "2020 Impact Factor: 11.429",
        url: "https://doi.org/10.15252/msb.20199110",
        year: 2020,
    },
    {
        key: "HuckaFinney2003",
        topics: ["SBML"],
        authors: "M. Hucka et al (43 authors, including J. Wagner)",
        title: "The Systems Biology Markup Language (SBML): a medium for representation and exchange of biochemical network models",
        journal: "Bioinformatics",
        volume: "19(4):524—531, 2003",
        impact: "2003 Impact Factor: 6.701",
        url: "https://doi.org/10.1093/bioinformatics/btg015",
        year: 2003,
    },
    {
        key: "KhatibiBabon2017",
        topics: ["Cancer"],
        authors: "S. Khatibi, J. Babon, J. Wagner, J.H. Manton, C.W. Tan., J. Zhu, S. Wormald and A.W. Burgess",
        title: "TGF-β and IL-6 family signalling crosstalk: an integrated model",
        journal: "Growth Factors",
        volume: "35(2—3):100—124, 2017",
        impact: "2017 Impact Factor: 1.800",
        url: "https://doi.org/10.1080/08977194.2017.1363746",
        year: 2017,
    },
    {
        key: "KhatibiZhu2017",
        topics: ["Cancer"],
        authors: "S. Khatibi, H.-J. Zhu, J. Wagner, C.W. Tan, J.H. Manton and A.W. Burgess",
        title: "Mathematical model of TGF-β signalling: feedback coupling is consistent with signal switching",
        journal: "BMC Systems Biology",
        volume: "11:48, 2017",
        impact: "2017 Impact Factor: 2.050",
        url: "https://doi.org/10.1186/s12918-017-0421-5",
        year: 2017,
    },
    {
        key: "HuFeng2007",
        topics: ["Cancer"],
        authors: "W. Hu, Z. Feng, L. Ma, J. Wagner, J.J. Rice, G. Stolovitzky, and A.J. Levine",
        title: "A single nucleotide polymorphism in the mdm2 gene disrupts the oscillation of p53 and mdm2 levels in cells",
        journal: "Cancer Research",
        volume: "67(6):2757—2765, 2007",
        impact: "2007 Impact Factor: 7.672",
        url: "https://doi.org/10.1158/0008-5472.CAN-06-2656",
        year: 2007,
    },
    {
        key: "WagnerMa2005",
        topics: ["Cancer"],
        authors: "J. Wagner, L. Ma, J.J. Rice, W. Hu, A. Levine and G.A. Stolovitzky",
        title: "p53–Mdm2 loop is controlled by a balance of its feedback strength and effective dampening using ATM and delayed feedback",
        journal: "IEE Proceedings Systems Biology",
        volume: "152(3):109—118, 2005",
        impact: "2005 Impact Factor: 1.955",
        url: "https://doi.org/10.1049/ip-syb:20050025",
        year: 2005,
    },
    {
        key: "MaWagner2005",
        topics: ["Cancer"],
        authors: "L. Ma, J. Wagner, J.J. Rice, A. Levine, W. Hu and G. Stolovitzky",
        title: "A plausible model for the digital response of p53 to DNA damage",
        journal: "Proceedings of the National Academy of Sciences",
        volume: "102(40): 14266—14271, 2005",
        impact: "2005 Impact Factor: 10.231",
        url: "https://doi.org/10.1073/pnas.0501352102",
        year: 2005,
    },
    {
        key: "GordonWeber2016",
        topics: ["Antibiotics"],
        authors: "S.E. Gordon, D.K. Weber, M.T. Downton, J. Wagner and M.A. Perugini",
        title: "Dynamic Modelling Reveals ‘Hotspots’ on the Pathway to Enzyme-Substrate Complex Formation",
        journal: "PLoS Computational Biology",
        volume: "2016",
        impact: "2014 Impact Factor: 4.620",
        url: "https://doi.org/10.1371/journal.pcbi.1004811",
        year: 2016,
    },
    {
        key: "SoaresDaCostaChristensen2015",
        topics: ["Antibiotics"],
        authors:
            "T.P. Soares da Costa, J.B. Christensen, S. Desbois, S.E. Gordon, R. Gupta, C.J. Hogan, T.G. Nelson, M.T. Downton, C.K. Ghardi, B.M. Abbott, J. Wagner, S. Panjikar and M.A. Perugini",
        title: "Quaternary structure analyses of an essential oligomeric enzyme",
        journal: "Methods in Enzymology",
        volume: "562, 205—223, 2015",
        impact: "2012 Impact Factor: 2.002",
        url: "https://doi.org/10.1016/bs.mie.2015.06.020",
        year: 2015,
    },
    {
        key: "HorDobson2013",
        topics: ["Antibiotics"],
        authors: "L. Hor, R.C.J. Dobson, M.T. Downton, J. Wagner, C.A. Hutton and M.A. Perugini",
        title: "Dimerization of Bacterial Diaminopimelate Epimerase is Essential for Catalysis",
        journal: "Journal of Biological Chemistry",
        volume: "288(13):9238—9248, 2013",
        impact: "2013 Impact Factor: 4.600",
        url: "https://doi.org/10.1074/jbc.M113.450148",
        year: 2013,
    },
    {
        key: "AtkinsonDogovski2013",
        topics: ["Antibiotics"],
        authors:
            "S.C. Atkinson, C. Dogovski, M.T. Downton, P.E. Czabotar, R.C.J. Dobson, J.A. Gerrard, J. Wagner and M.A. Perugini",
        title: "Structural, kinetic and computational investigation of Vitis vinifera DHDPS reveals new insight into the mechanism of lysine-mediated allosteric inhibition",
        journal: "Plant Molecular Biology",
        volume: "81(4-5)431—446, 2013",
        impact: "2012 Impact Factor; 4.072",
        url: "https://doi.org/10.1007/s11103-013-0014-7",
        year: 2013,
    },
    {
        key: "AtkinsonDogovski2012",
        topics: ["Antibiotics"],
        authors:
            "S.C. Atkinson, C. Dogovski, M.T. Downton, F.G. Pearce, J.A. Gerrard, R.C.J. Dobson, J. Wagner and M.A. Perugini",
        title: "Crystal, solution and in silico structural studies of dihydrodipicolinate synthase from the common grapevine",
        journal: "PLoS ONE",
        volume: "7(6):e38318, 2012",
        impact: "2012 Impact Factor: 3.730",
        url: "https://doi.org/10.1371/journal.pone.0038318",
        year: 2012,
    },
    {
        key: "DogovskiAtkinson2012",
        topics: ["Antibiotics"],
        authors:
            "C. Dogovski, S.C. Atkinson, S.R. Dommaraju, M. Downton, L. Hor, S. Moore, J.J. Paxman, M.G. Peverelli, T.W. Qiu, M. Reumann, T. Siddiqui, N.L. Taylor, J. Wagner, J.M. Wubben and M.A. Perugini",
        title: "Enzymology of Bacterial Lysine Biosynthesis",
        journal: "In Biochemistry",
        volume: "ISBN 979-953-307-484-8, InTech, 2012",
        url: "https://www.intechopen.com/chapters/30570",
        year: 2012,
    },
    {
        key: "HarrerKim2015",
        topics: ["Nanosensors"],
        authors:
            "S. Harrer, S. Kim, C. Schieber, S. Kannam, N. Gunn, S. Moore, D. Scott, R. Bathgate, S. Skafidas and J. Wagner",
        title: "Label-free screening of single biomolecules through resistive pulse sensing technology for precision medicine applications",
        journal: "Nanotechnology",
        volume: "26 182502, 2015",
        impact: "2013 Impact Factor: 3.672",
        url: "https://doi.org/10.1088/0957-4484/26/18/182502",
        year: 2015,
    },
    {
        key: "KimKannam2014",
        topics: ["Nanosensors"],
        authors: "S.C Kim, S.K. Kannam, S. Harrer, S. Moore, M.T. Downton and J. Wagner",
        title: "Geometry dependence of conductance drop in nanopore in the presence of a particle",
        journal: "Physical Review E",
        volume: "89, 042702, 2014",
        impact: "2014 Impact Factor: 2.326",
        url: "https://doi.org/10.1103/PhysRevE.89.042702",
        year: 2014,
    },
    {
        key: "KannamKim2014",
        topics: ["Nanosensors"],
        authors: "S.K. Kannam, S.C. Kim, P.R. Rogers, N. Gunn, J. Wagner, S. Harrer and M.T. Downton",
        title: "Sensing of protein molecules through nanopores: A molecular dynamics study",
        journal: "Nanotechnology",
        volume: "25 155502, 2014",
        impact: "2014 Impact Factor: 3.672",
        url: "https://doi.org/10.1088/0957-4484/25/15/155502",
        year: 2014,
    },
    {
        key: "KannamDownton2013",
        topics: ["Nanosensors"],
        authors:
            "S.K. Kannam, M.T. Downton, N. Gunn, S.C. Kim, P.R. Rogers, C. Schieber, J.S. Baldauf, J.M. Wagner, D. Scott, R. Bathgate, S. Skafidas and S. Harrer",
        title: "Nanosensors for next generation drug screening",
        journal: "Proceedings of SPIE",
        volume: "8923, Micro/Nano Materials, Devices, and Systems, 89230I",
        url: "https://doi.org/10.1117/12.2033737",
        year: 2013,
    },
    {
        key: "OehmeDoblin2015",
        topics: ["Cellulose", "HPC"],
        authors: "D.P. Oehme, M.S. Doblin, J. Wagner, A. Bacic, M.T. Downton and M.J. Gidley",
        title: "Gaining insight into Macrofibril Formation by Simulating Cellulose Microfibril Adsorption",
        journal: "Cellulose",
        volume: "2015, 22(6):3501-3520",
        impact: "2014 Impact Factor: 3.573",
        url: "https://doi.org/10.1007/s10570-015-0778-9",
        year: 2015,
    },
    {
        key: "SchwerdtMacKenzie2015",
        topics: ["Cellulose", "HPC"],
        authors:
            "J.G. Schwerdt, K. MacKenzie, F. Wright, D. Oehme, J.M. Wagner, A.J. Harvey, N.J. Shirley, R.A. Burton, M. Schreiber, C. Halpin, J. Zimmer, D.F. Marshall, R. Waugh and G.B. Fincher",
        title: "Evolutionary Dynamics of the Cellulose Synthase Gene Superfamily in Grasses",
        journal: "Plant Physiology",
        volume: "168(3):968–983, 2015",
        impact: "2014 Impact Factor: 7.394",
        url: "https://doi.org/10.1104/pp.15.00140",
        year: 2015,
    },
    {
        key: "OehmeDownton2015",
        topics: ["Cellulose", "HPC"],
        authors: "D.P. Oehme, M.T. Downton, M.S. Doblin, J. Wagner, M.J. Gidley and A. Bacic",
        title: "Unique aspects of the structure and dynamics of elementary Iβ cellulose microfibrils revealed by computational simulations",
        journal: "Plant Physiology",
        volume: "168(1):3—17, 2015",
        impact: "2014 Impact Factor: 7.394",
        url: "https://doi.org/10.1104/pp.114.254664",
        year: 2015,
    },
    {
        key: "FallWagner2004",
        topics: ["Fertilisation"],
        authors: "C.P. Fall, J. Wagner, L.M. Loew and R.L. Nuccitelli",
        title: "Cortically restricted production of IP3 leads to propagation of the fertilization Ca2+ wave along the cell surface in a model of the Xenopus egg",
        journal: "Journal of Theoretical Biology",
        volume: "231(4):487—496, 2004",
        impact: "2012 Impact Factor: 1.683",
        url: "https://doi.org/10.1016/j.jtbi.2004.06.019",
        year: 2004,
    },
    {
        key: "WagnerFall2004",
        topics: ["Fertilisation"],
        authors:
            "J. Wagner, C.P. Fall, F. Hong, C.E. Sims, N.L. Allbritton, R.A. Fontanilla, I.I. Moraru, L.M. Loew, and R. Nuccitelli",
        title: "A wave of IP3 production accompanies the fertilization Ca2+ wave in the egg of the frog, Xenopus laevis: theoretical and experimental support",
        journal: "Cell Calcium",
        volume: "35:433—447, 2004",
        impact: "2004 Impact Factor: 5.186",
        url: "https://doi.org/10.1016/j.ceca.2003.10.009",
        year: 2004,
    },
    {
        key: "WagnerLi1998",
        topics: ["Fertilisation"],
        authors: "J. Wagner, Y.-X. Li, J. Pearson and J. Keizer",
        title: "Simulation of the fertilization Ca2+ wave in Xenopus laevis eggs",
        journal: "Biophysical Journal",
        volume: "75:2088—2097, 1998",
        impact: "1998 Impact Factor: 4.524",
        url: "https://doi.org/10.1016/s0006-3495(98)77651-9",
        year: 1998,
    },
    {
        key: "FallWagner2000",
        topics: ["Calcium"],
        authors: "C. Fall, J. Wagner, R. Nuccitelli and J. Pearson",
        title: "Progress in Ca2+ dynamics: Small temporal and spatial scales drive macroscopic dynamics",
        journal: "Cell Calcium",
        volume: "27(6):363—364, 2000",
        impact: "2000 Impact Factor: 3.711",
        url: "https://doi.org/10.1054/ceca.2000.0134",
        year: 2000,
    },
    {
        key: "SmithWagner1996",
        topics: ["Calcium"],
        authors: "G.D. Smith, J. Wagner and J. Keizer",
        title: "Validity of the rapid buffering approximation near a point source of calcium ions",
        journal: "Biophysical Journal",
        volume: "70:2527—2539, 1996",
        impact: "1996 Impact Factor: 4.713",
        url: "https://doi.org/10.1016/S0006-3495(96)79824-7",
        year: 1996,
    },
    {
        key: "WagnerKeizer1994",
        topics: ["Calcium"],
        authors: "J. Wagner and J. Keizer",
        title: "Effects of rapid buffers on Ca2+ diffusion and Ca2+ oscillations",
        journal: "Biophysical Journal",
        volume: "67:447—456, 1994",
        impact: "1994 Impact Factor: 4.427",
        url: "https://doi.org/10.1016/S0006-3495(94)80500-4",
        year: 1994,
    },
    {
        key: "WeberYao2015",
        topics: ["Miscellany"],
        authors: "D.K. Weber, S. Yao, N. Rojko, G. Anderluh, T.P. Lybrand, M.T. Downton, J. Wagner and F. Separovic",
        title: "Characterization of the lipid-binding site of equinatoxin II in micelles by NMR and molecular dynamics simulation",
        journal: "Biophysical Journal",
        volume: "108(8): 1987—1996, 2015",
        impact: "2014 Impact Factor: 3.832",
        url: "https://doi.org/10.1016/j.bpj.2015.03.024",
        year: 2015,
    },
    {
        key: "GoudeyAbedini2015",
        topics: ["Genomics", "HPC"],
        authors:
            "B. Goudey, M. Abedini, J.L. Hopper, M. Inouye, E. Makalic, D.F. Schmidt, J. Wagner, Z. Zhou, J. Zobel and M. Reumann",
        title: "High performance computing enabling exhaustive analysis of higher order single nucleotide polymorphism interaction in Genome Wide Association Studies",
        journal: "Health Information Science and Systems 2015",
        volume: "3:S3",
        url: "https://doi.org/10.1186/2047-2501-3-S1-S3",
        year: 2015,
    },
    {
        key: "ReumannMakalic2012",
        topics: ["Genomics", "HPC"],
        authors:
            "M. Reumann, E. Makalic, B.W. Goudey, M. Inouye, A. Bickerstaffe, M. Bui, D.J. Park, M.K. Kapuscinski, D.F. Schmidt, Z. Zhou, G. Qian, J. Zobel, J. Wagner and J.L. Hopper",
        title: "Supercomputing enabling exhaustive statistical analysis of genome wide association study data: preliminary results",
        journal: "34th Annual International IEEE EMBS Conference, 2012.",
        volume: "",
        url: "https://doi.org/10.1109/EMBC.2012.6346166",
        year: 2012,
    },
    {
        key: "TrongMotley2017",
        topics: ["Neuroscience"],
        authors: "T. M. Hoang Trong, S. E. Motley, J. Wagner, R. R. Kerr and J. Kozloski",
        title: "Dendritic spines modify action potential back-propagation in a multicompartment neuronal model",
        journal: "IBM Journal of Research and Development",
        volume: "61(2/3): 11:1 - 11:13, 2017",
        url: "https://doi.org/10.1147/JRD.2017.2679558",
        year: 2017,
    },
    {
        key: "KozloskiWagner2011",
        topics: ["HPC", "Neuroscience"],
        authors: "J. Kozloski and J. Wagner",
        title: "An ultrascalable solution to large-scale neural tissue simulation",
        journal: "Frontiers in Neuroinformatics",
        volume: "5:15, 2011",
        url: "https://doi.org/10.3389/fninf.2011.00015",
        year: 2011,
    },
    {
        key: "RaoCecchi2009",
        topics: ["Cancer", "HPC"],
        authors: "J. Wagner and K. Jordan",
        title: "Utilizing Parallel Processing in Computational Biology Applications",
        journal: "High-Throughput Image Reconstruction and Analysis",
        // journal: "Artech House",
        volume: "A.R. Rao and G. Cecchi, eds. Artech House, 2009.",
        url: "https://us.artechhouse.com/High-Throughput-Image-Reconstruction-and-Anlaysis-P1233.aspx",
        year: 2009,
    },
    {
        key: "MaayanCecchi2008",
        topics: ["Miscellany"],
        authors: "Ma’ayan, G.A. Cecchi, J. Wagner, A.R. Rao, R. Iyengar, G. Stolovitzky",
        title: "Ordered cyclic motifs contribute to dynamic stability in biological and engineered networks",
        journal: "Proceedings of the National Academy of Sciences",
        volume: "105(49): 19234—19239, 2008",
        impact: "2008 Impact Factor: 9.380",
        url: "https://doi.org/10.1073/pnas.0805344105",
        year: 2008,
    },
    {
        key: "WagnerStolovitzky2008",
        topics: ["Miscellany"],
        authors: "J. Wagner and G. Stolovitzky",
        title: "Stability and time-delay modeling of negative feedback loops",
        journal: "Proceedings of the IEEE",
        volume: "96(8):1398—1410, 2008",
        impact: "2011 Impact Factor: 4.613",
        url: "https://doi.org/10.1109/JPROC.2008.925427",
        year: 2008,
    },
    {
        key: "OEIS2006",
        topics: ["Miscellany"],
        authors: "A. Ma’ayan, G.A. Cecchi, J. Wagner, A.R. Rao, A. Lipshtat, R. Iyengar, G. Stolovitzky",
        title: "Sequence A117747",
        journal: "The On-Line Encyclopedia of Integer Sequences",
        volume: "April 28, 2006.",
        url: "https://oeis.org/A117747",
        year: 2006,
    },
    {
        key: "CCB2002",
        topics: ["Miscellany"],
        authors: "C.P. Fall, E.S. Marland, J.M. Wagner and J. J. Tyson (Editors",
        title: "Computational Cell Biology",
        journal: "Springer-Verlag, New York",
        volume: "2002",
        url: "https://www.amazon.com/Computational-Biology-Interdisciplinary-Applied-Mathematics/dp/0387953698",
        year: 2002,
    },
    {
        key: "SchaffSlepchenko2001",
        topics: ["Miscellany"],
        authors: "J.C. Schaff, B.M. Slepchenko, Y.-S. Choi, J. Wagner, D. Resasco and L.M. Loew",
        title: "Analysis of non-linear dynamics on arbitrary geometries with the Virtual Cell",
        journal: "Chaos",
        volume: "11(1):115—131, 2001",
        impact: "2001 Impact Factor: 1.935",
        url: "https://doi.org/10.1063/1.1350404",
        year: 2001,
    },
    {
        key: "KeizerFox1993",
        topics: ["Miscellany"],
        authors: "J. Keizer, R. Fox, and J. Wagner",
        title: "On the amplification of molecular fluctuations for nonstationary systems: hydrodynamic fluctuations for the Lorenz model",
        journal: "Physics Letters A",
        volume: "175:17—22, 1993",
        impact: "1993 Impact Factor: 1.149",
        url: "https://doi.org/10.1016/0375-9601(93)90847-S",
        year: 1993,
    },
    {
        key: "DepnerRizwan1991",
        topics: ["Miscellany"],
        authors: "T.A. Depner, S. Rizwan, A.Y. Cheer, J.M. Wagner and L.A. Eder",
        title: "High venous urea concentrations in the opposite arm: a consequence of hemodialysis-induced compartment disequilibrium",
        journal: "ASAIO Journal",
        volume: "37(3):M141-3, 1991",
        impact: "2012 Impact Factor: 1.491",
        url: "https://pubmed.ncbi.nlm.nih.gov/1751084/",
        year: 1991,
    },
]

export default publications
