const teaching = [
    {
        dates: "2018 - 2020",
        from: "2018",
        to: "2020",
        title: "So, you want to be a Master Inventor, eh?",
        organisation: "IBM Research-Australia",
    },
    {
        dates: "2017",
        from: "2017",
        to: "",
        title: "Building Your Eminence and Career in Research and IBM Research",
        organisation: "IBM Research-Australia",
    },
    {
        dates: "2016 - 2019",
        from: "2016",
        to: "2019",
        title: "Invent! Collaborate! Patent!",
        organisation: "IBM Australia",
    },
    {
        dates: "2013 - 2016",
        from: "2013",
        to: "2016",
        TouchList: "2013 - 2016",
        title: "Parallel and Multicore Computing (COMP90025)",
        organisation: "University of Melbourne",
    },
    {
        dates: "2011 - 2013",
        from: "2011",
        to: "2013",
        title: "Two-week section of Neural Information Processing (BMEN90002)",
        organisation: "University of Melbourne",
    },
    {
        dates: "1999 - 2002",
        from: "1999",
        to: "2002",
        TouchList: "1999 - 2002",
        title: "Neurophysiology Conference",
        organisation: "School of Medicine, University of Connecticut",
    },
    {
        dates: "1999 - 2002",
        from: "1999",
        to: "2002",
        title: "Axonology Laboratory",
        organisation: "School of Medicine, University of Connecticut",
    },
    {
        dates: "1993 - 1997",
        from: "1993",
        to: "1997",
        title: "C/C++/High Performance and Scientific Computing",
        organisation: "University of California, Davis",
    },
    {
        dates: "1997",
        from: "1997",
        to: "",
        title: "Numerical Analysis Computer Laboratory",
        organisation: "Department of Mathematics, University of California, Davis",
    },
    {
        dates: "1995",
        from: "1995",
        to: "",
        title: "Ordinary Differential Equations",
        organisation: "Department of Mathematics, University of California, Davis",
    },
    {
        dates: "1995",
        from: "1995",
        to: "",
        title: "Ordinary Differential Equations Computer Lab",
        organisation: "Department of Mathematics, University of California, Davis",
    },
    {
        dates: "1994 - 1995",
        from: "1994",
        to: "1995",
        title: "Numerical Analysis (Teaching Assistant)",
        organisation: "Department of Mathematics, University of California, Davis",
    },
]

export default teaching
